Api/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('',Home, name='Home'),
    # path('administrador/', Administrador, name='administrador'),
    path('logout/', Salir, name='logouts'),
    path('register/', Register, name='Register'),
    path('Registro/', Registro, name='Registro'),
    path('Producto/', producto, name='Producto'),
    path('Modificar/<int:codigo>/', Modificar, name='Modificar'),
    path('eliminar_producto/<int:codigo>/', eliminar_producto, name='eliminar_producto'),
]

Project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Api.urls')),
    path('accounts/',include('django.contrib.auth.urls'))
]
 
if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Api/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here
class Producto(models.Model):
    Codigo = models.AutoField(primary_key=True)
    Nombre = models.CharField(max_length=100)
    Descripcion = models.TextField()
    Precio = models.DecimalField(max_digits=10, decimal_places=2)
    Stock = models.IntegerField()
    Imagen = models.ImageField(upload_to="Musimg", null=True)

    def __int__(self):
        return self.Codigo

# class Cliente(models.Model):
#     nombre = models.CharField(max_length=100)
#     apellido = models.CharField(max_length=100)
#     email = models.EmailField()
#     telefono = models.CharField(max_length=15)

#     def __str__(self):
#         return f"{self.nombre} {self.apellido}"

Api/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm

class CustomUserCreationForm(UserCreationForm):
    pass
        
class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = "__all__"
        widgets = {
            'Imagen': forms.FileInput(),    
        }

Api/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required 
from django.contrib.auth import logout,login,authenticate
from .forms import CustomUserCreationForm 
from .forms import *
import time
from django.db.models import Q
from .models import *
from django.contrib import messages

from django.contrib.admin.views.decorators import staff_member_required

# Create your views here.
def Home(request):
    ultimos_productos = Producto.objects.order_by('-Codigo')[:3]
    low_stock_count = Producto.objects.filter(Stock__lt=5).count()
    data = {
        'ultimos': ultimos_productos,
        'low_stock_count': low_stock_count
    }
    return render (request, "index.html",data)

@login_required


def Salir(request):
    logout(request)
    return redirect('Home')


from django.contrib import messages

def Register(request):
    if request.method == "POST":
        query = CustomUserCreationForm(data=request.POST)
        if query.is_valid():
            query.save()
            user = authenticate(username=query.cleaned_data['username'],
                                password=query.cleaned_data['password1'])
            login(request, user)
            return redirect('Home')
        else:
            for field, errors in query.errors.items():
                for error in errors:
                    messages.error(request, error)
    else:
        query = CustomUserCreationForm()

    return render(request, 'registration/register.html', {'signup': query})


def producto(request):
    query= Producto.objects.all()
    filtroNom = request.GET.get('filtroNom')
    filtroDes = request.GET.get('filtroDes')

    condiciones = Q()
    if filtroNom:
        condiciones |= Q(Nombre__icontains=filtroNom)
    if filtroDes:
        condiciones |= Q(Descripcion__contains=filtroDes)
    
    if condiciones:
        query = query.filter(condiciones)

    return render(request, "pages/Productos.html", {"productos": query})

@staff_member_required

def Registro(request):
    query = Producto.objects.order_by('-Codigo')
    data={
        'productos': query,
        'regproducto':ProductoForm()
    }
    if request.method == 'POST':
        formulario = ProductoForm(data=request.POST, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Producto agregado correctamente")
        else:
            data['regproducto'] = ProductoForm()
    return render(request, 'Pages/Registro.html', data)

def Modificar(request, codigo):
    producto = Producto.objects.get(Codigo=codigo)
    data = {
        'modproducto': ProductoForm(instance=producto)
    }

    if request.method == 'POST':
        formulario = ProductoForm(data=request.POST, files=request.FILES, instance=producto)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Modificado correctamente!")
            return redirect('Registro')

    return render(request, 'Pages/Modificar.html', data)

def eliminar_producto(request, codigo):
    producto = Producto.objects.get(Codigo=codigo)
    producto.delete()
    messages.success(request, "¡Eliminado correctamente!")
    return redirect('Registro')

Api/templates/Pages/Modificar.html
{% extends "index.html" %}
{% block content %}
<div class="contenedor-formulario">
    <form method="POST" enctype="multipart/form-data" class="formu">
        {% csrf_token %}
        <div class="title">
            <h2>Modificar Producto</h2>
        </div>
        <div class="campos-formulario">
            <div>
                <label for="id_Nombre">Nombre:</label>
                {{ modproducto.Nombre }}
            </div>
            <div>
                <label for="id_Descripcion">Descripción:</label>
                {{ modproducto.Descripcion }}
            </div>
            <div>
                <label for="id_Precio">Precio:</label>
                {{ modproducto.Precio }}
            </div>
            <div>
                <label for="id_Stock">Stock:</label>
                {{ modproducto.Stock }}
            </div>
            <div class="pickimage">
                <label for="id_Imagen" class="btnsnd">Elige una imagen</label>
                {{ modproducto.Imagen.as_widget }}
            </div>
            <div style="display: flex; justify-content: flex-start; margin: auto; margin-top: 15px;" class="previews">
                <div>
                    {% if modproducto.instance.Imagen %}
                        <p>Imagen actual:</p>
                        <img src="{{ modproducto.instance.Imagen.url }}" alt="Imagen actual" id="imgActual" style="max-height: 150px; border: 1px solid #ccc;">
                    {% endif %}
                </div>
                <div>
                    <p>Imagen nueva:</p>
                    <img id="imgPreview" style="height: 150px; border: 1px dashed #ccc; display: block; width: 150px; max-height: 150px; max-width: 150px;">
                </div>
            </div>
        </div>
        <input type="submit" value="Guardar cambios" class="btnsnd">
    </form>
</div>

<script>
document.addEventListener("DOMContentLoaded", function() {
    const inputFile = document.getElementById("id_Imagen");
    const preview = document.getElementById("imgPreview");

    if (inputFile) {
        inputFile.addEventListener("change", function() {
            const file = inputFile.files[0];
            if (file) {
                const reader = new FileReader();
                reader.onload = function(e) {
                    preview.src = e.target.result;
                    preview.style.display = "block";
                };
                reader.readAsDataURL(file);
            } else {
                preview.src = "";
                preview.style.display = "none";
            }
        });
    }
});
</script>


{% endblock %}

Api/templates/Pages/Productos.html
{% extends "index.html" %}

{% block content %}
<div class="buscador">
    <form action="" method="get" class="formu-buscador">
        <div class="title">
            <h2>Buscar Álbum</h2>
        </div>
        <div class="grupo-busqueda">
            <div class="campo-busqueda">
                <label for="filtroNomAlbum">Nombre del álbum:</label>
                <input type="text" name="filtroNom" id="filtroNomAlbum" placeholder="Ej. Thriller">
            </div>
            <div class="campo-busqueda">
                <label for="filtroNomArtista">Nombre del artista:</label>
                <input type="text" name="filtroDes" id="filtroNomArtista" placeholder="Ej. Michael Jackson">
            </div>
            <div class="campo-boton">
                <input type="submit" value="Buscar">
            </div>
        </div>
            <div class="tarjetas">
                {% for i in productos %}
                <div class="tar">
                    <img src="{{i.Imagen.url}}" alt="">
                    <div class="nomprec truncate">
                        <p style="max-width: 75%; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; font-size: 25px;">{{i.Nombre}}</p>
                        <p class="precio" style="font-size: 15px;">${{i.Precio}}</p>
                    </div>
                    <div class="nomprec">
                        <p style="font-size: 15px;">Cantidad</p>
                        <p>{{i.Stock}}</p>
                    </div>
                    <p class="descripcion" style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis; max-width: 320px;">{{i.Descripcion}}</p>
                </div>
            {% endfor %}
        </div>
{% endblock content %}

Api/templates/Pages/Registro.html
{% extends "index.html" %}
{% load static %}
{% block content %}
<div class="contenedor-formulario">
    <form action="" method="POST" enctype="multipart/form-data" class="formu">
        {% csrf_token %}
        <div class="title">
            <h2>Registrar Producto</h2>
        </div>
        <div class="campos-formulario">
            <div>
                <label for="id_Nombre">Nombre:</label>
                {{ regproducto.Nombre }}
            </div>
            <div>
                <label for="id_Descripcion">Descripción:</label>
                {{ regproducto.Descripcion }}
            </div>
            <div>
                <label for="id_Precio">Precio:</label>
                {{ regproducto.Precio }}
            </div>
            <div>
                <label for="id_Stock">Stock:</label>
                {{ regproducto.Stock }}
            </div>
            <div class="pickimage">
                <label for="id_Imagen" class="btnsnd usarbtn">Elegir una imágen</label>
                {{ regproducto.Imagen }}
                <img id="imgPreview" style="max-height: 150px; border: 1px dashed #ccc; margin-top: 10px; height: 150px; width: 150px;" alt="Vista previa">
            </div>
        </div>
        <button type="submit" value="registro" id="boton" class="boton-registrar btnsnd usarbtn">Registrar Producto</button>
    </form>
    <div class="tabla-scroll">
        <table>
            <thead>
                <tr>
                    <th>
                        <span>Nombre</span>
                    </th>
                    <th>
                        <span>Descripción</span>
                    </th>
                    <th>
                        <span>Precio</span>
                    </th>
                    <th>
                        <span>Stock</span>
                    </th>
                    <th class="acciones">
                        <span>Acciones</span>
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for i in productos %}
                <tr>
                    <td>
                        <span style="font-weight: bolder;">{{i.Nombre}}</span>
                    </td>
                    <td>
                        <span>{{i.Descripcion}}</span>
                    </td>
                    <td class="precioadmin">
                        <span>{{i.Precio}}</span>
                    </td>
                    <td class="stock">
                        <span>{{i.Stock}}</span>
                    </td>
                    <td class="actions">
                        <a href="{% url 'Modificar' i.Codigo %}" style="margin-right: 25px;" class="modificar">✏️</a>
                        <a href="{% url 'eliminar_producto' i.Codigo %}" class="eliminar">🗑️</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

Api/templates/index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'src/images/favicon.png' %}" type="image/x-icon">
    <title>MusicStore AR</title>
</head>

<body>
    <header>
        <div>
            <a href="" class="logo">
                <img src="{% static 'src/images/favicon.png' %}" alt="">
            </a>
        </div>
        <button class="btn-open btnsnd" onclick="abrirSidebar()">☰</button>
        <nav class="navbar desktop-navbar">
            <ul>
                <li><a href="{% url 'Home' %}" class="btnsnd"><span>Inicio</span></a></li>
                <li><a href="{% url 'Producto' %}" class="btnsnd"><span>Productos</span></a></li>
                <li><a href="#contacto" class="btnsnd"><span>Contacto</span></a></li>
                {% if user.is_authenticated %}
                {% if user.is_staff %}
                <li><a href="{% url 'Registro' %}" class="btnsnd" style="gap: 5px;">
                    <span>Administrar</span>
                    {% if low_stock_count > 0 %}
                    <span style="color: #fff; font-weight: bold; margin-top: 2px; background: red; border-radius: 100px; padding: 5px; border: 2px solid #fff;">{{ low_stock_count }}</span>
                    {% endif %}
                </a></li>
                {% endif %}
                <li><a href="{% url 'logouts' %}" class="btnsnd"><span>Cerrar Sesión</span></a></li>
                {% else %}
                <li><a href="{% url 'login' %}" class="btnsnd"><span>Ingresar</span></a></li>
                {% endif %}
            </ul>
        </nav>
        <nav class="sidebar" id="sidebar">
            <a href="javascript:void(0)" class="btn-close btnsnd" onclick="cerrarSidebar()">X</a>
            <ul>
                <li><a href="{% url 'Home' %}" class="btnsnd"><span>Inicio</span></a></li>
                <li><a href="{% url 'Producto' %}" class="btnsnd"><span>Productos</span></a></li>
                <li><a href="#contacto" class="btnsnd" onclick="cerrarSidebar()"><span>Contacto</span></a></li>
                {% if user.is_authenticated %}
                {% if user.is_staff %}
                <li><a href="{% url 'Registro' %}" class="btnsnd" style="gap: 5px;">
                    <span>Administrar</span>
                    {% if low_stock_count > 0 %}
                    <span style="color: #fff; font-weight: bold; margin-top: 2px; background: red; border-radius: 100px; padding: 5px; border: 2px solid #fff;">{{ low_stock_count }}</span>
                    {% endif %}
                </a></li>
                {% endif %}
                <li><a href="{% url 'logouts' %}" class="btnsnd"><span>Cerrar Sesión</span></a></li>
                {% else %}
                <li><a href="{% url 'login' %}" class="btnsnd"><span>Ingresar</span></a></li>
                {% endif %}
            </ul>
        </nav>

    </header>
    {% block content %}
    <main>
        <div class="title" style="margin-bottom: 30px; border-bottom: 3px solid #000;">
            <h2>Ultimas adiciones</h2>
        </div>
        <div class="carrusel-productos">
            {% for i in ultimos %}
            <div class="tar">
                <img src="{{i.Imagen.url}}" alt="Imagen de {{i.Nombre}}">
                <div class="nomprec">
                    <p class="titulo-album">{{i.Nombre}}</p>
                    <p class="precio">${{i.Precio}}</p>
                </div>
                <div class="nomprec">
                    <span>Cantidad:</span>
                    <p>{{i.Stock}}</p>
                </div>
                <p class="descripcion-album">{{i.Descripcion}}</p>
            </div>
            {% endfor %}
        </div>

        <div class="ver-mas">
            <a href="{% url 'Producto' %}" class="boton-vermas">
                <span>Ver Más</span>
            </a>
        </div>
    </main>
    {% endblock %}

    <footer id="contacto" class="footer-contacto">
        <div class="footer-contenido">
            <div class="footer-integrantes">
                <h3>Integrantes del Proyecto</h3>
                <ul>
                    <li>
                        Gonzalo Alegre<br>
                        <a href="https://www.instagram.com/gnzzaar?igsh=aW4zOXl6OGszajVj"
                            class="instagram-link">Instagram personal</a>
                    </li>
                    <li>
                        Abril Castro<br>
                        <a href="https://www.instagram.com/apfelsoja?igsh=MXJsOHU2ZGVnZncxYw=="
                            class="instagram-link">Instagram personal</a>
                    </li>
                    <li>
                        Matias Molina<br>
                        <a href="https://www.instagram.com/mts_mlna?igsh=dzIwaDBkam85MGg1"
                            class="instagram-link">Instagram personal</a>
                    </li>
                    <li>
                        Bruno Sánchez<br>
                        <a href="https://www.instagram.com/grumno_eze?igsh=YXJidHF1bXlmb3F1"
                            class="instagram-link">Instagram personal</a>
                    </li>
                </ul>
            </div>

            <div class="footer-colegio">
                <h3>Contacto del Colegio</h3>
                <p>E.E.S.T. N°1 Esteban Echeverría</p>
                <p>Teléfono: <span class="colegio-dato">[Número de teléfono]</span></p>
                <p>Dirección: <span class="colegio-dato">Güemes 2051 - Monte Grande</span></p>
                <p><a href="https://sites.google.com/view/tecnica1montegrande/inicio" class="web-link">Sitio Web del
                        Colegio</a></p>
            </div>
        </div>

        <div class="footer-derechos">
            <p>© 2025 Todos los derechos reservados - Proyecto Escolar 2025 </p>
        </div>
        <button id="btn-ir-arriba" title="Volver arriba" class="btnsnd">↑</button>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q"
        crossorigin="anonymous">
    </script>
<audio src="{% static 'src/sound/hover.ogg' %}" id="hoversound" preload="auto"></audio>
<audio src="{% static 'src/sound/click.ogg' %}" id="clicksound" preload="auto"></audio>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="{% static 'src/javascript/main.js' %}"></script>
{% if messages %}
    {% for m in messages %}
        <script>
            Swal.fire({
                title: "{{m}}",
            })
        </script>
    {% endfor %}
{% endif %}

<script>
    function abrirSidebar() {
        document.getElementById("sidebar").style.width = "100%";
    }

    function cerrarSidebar() {
        document.getElementById("sidebar").style.width = "0";
    }
</script>

</body>

</html>